version: '3.1'

services:
  in-memory-db:
    container_name: 'redis-app'
    image: redis:7.0.8
    ports:
      - "6379:6379"
    network_mode: 'host'
  redis-insight:
    container_name: 'redis-insight'
    image: redislabs/redisinsight:1.6.3
    ports:
      - "8001:8001"
      - "6379:6379"
    network_mode: 'host'